[build]
  command = "npm install && npm install vite@5.1.4 --save-dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 