[build]
  command = "cd DarwinAI-LeadGen && npm install && npm run build"
  publish = "DarwinAI-LeadGen/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 