[build]
  command = "npm install && ./node_modules/.bin/tsc && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  GO_VERSION = ""
  PHP_VERSION = ""
  PYTHON_VERSION = ""
  RUBY_VERSION = ""
  NPM_VERSION = "9.8.1"
  MISE_SETTINGS = "idiomatic_version_file_enable_tools=node"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 